version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Install phase is starting...
      - yum update -y
      - yum install -y maven
  build:
    commands:
      - echo Build phase is starting...
      - mvn clean package
  post_build:
    commands:
      - echo Post build phase is starting...
      - echo Build completed successfully.
